class UniversityRunner
{
	public static void main(String[] values)
	{
		String colleges[]={null,"Adichunchanagiri Institute of Technology",
		"Acharya College of Engineering", "National Institute of Technology Karnataka, Surathkal",
    "Indian Institute of Technology Dharwad",
    "International Institute of Information Technology, Bangalore",
    "Visvesvaraya Technological University, Belagavi",
    "Indian Institute of Science, Bangalore",
    "R.V. College of Engineering, Bangalore",
    "Manipal Institute of Technology, Manipal",
    "M.S. Ramaiah Institute of Technology, Bangalore",
    "BMS College of Engineering, Bangalore",
    "PES University, Bangalore",
    "IIIT Bangalore",
    "Siddaganga Institute of Technology, Tumkur",
    "Christ University – Faculty of Engineering, Bangalore",
    "Jain University – School of Engineering & Technology, Bangalore",
    "Canara Engineering College, Benjanapadavu",
    "SJCE – Sri Jayachamarajendra College of Engineering, Mysore",
    "NIE – The National Institute of Engineering, Mysore",
    "SDM College of Engineering and Technology, Dharwad",
    "Dayananda Sagar College of Engineering, Bangalore",
    "Bangalore Institute of Technology, Bangalore",
    "Don Bosco Institute of Technology, Bangalore",
    "HKBK College of Engineering, Bangalore",
    "East Point Group of Institutions, Bangalore",
    "BNM Institute of Technology, Bangalore",
    "Nitte Meenakshi Institute of Technology, Bangalore",
    "PES College of Engineering, Mandya",
    "Bapuji Institute of Engineering & Technology, Davangere",
    "KLE Institute of Technology, Hubli",
    "SECAB Institute of Engineering & Technology, Bijapur",
    "MVJ College of Engineering, Bangalore",
    "CMR Institute of Technology, Bangalore",
    "Acharya Institute of Technology, Bangalore",
    "RV Institute of Technology and Management, Bangalore",
    "Maharaja Institute of Technology, Mysore",
    "Acharya & BM Reddy College of Engineering, Bangalore",
    "Shirdi Sai Engineering College, Bangalore",
    "Trinity College of Engineering & Research, Pune (affiliate in Karnataka)",
    "Bapuji Institute of Engineering & Technology, Ramesh Nagar",
    "Kuvempu University College of Engineering, Shivamogga",
    "Channabasaveshwara Institute of Technology, Gubbi",
    "Government Engineering College, Haveri",
    "Government Engineering College, Kushalnagar",
    "Government Engineering College, Raichur",
    "Government Engineering College, Chamarajanagar",
    "Government Engineering College, Hassan",
    "Government Engineering College, Karwar",
    "Government Engineering College, Gangavathi",
    "Oxford College of Engineering, Bangalore",
    "Alliance University College of Engineering, Bangalore",
    "JSS Academy of Technical Education, Bangalore",
    "KLE Technological University, Hubli",
    "P.E.S. Institute of Technology and Management, Shivamogga",
    "Bangalore City College of Engineering and Technology",
    "RNS Institute of Technology, Bangalore",
    "Alpha College of Engineering, Bangalore",
    "Garden City College of Engineering, Bangalore",
    "The Oxford College of Engineering, Bangalore",
    "Ramaiah Institute of Technology – School of Engineering",
    "Sai Vidya Institute of Technology, Bangalore",
    "Bharatesh Institute of Technology, Belagavi",
    "Basaveshwar Engineering College, Bagalkot",
    "Sahyadri College of Engineering & Management, Mangalore",
    "Alva’s Institute of Engineering & Technology, Moodbidri",
    "Sri Venkateshwara College of Engineering, Bengaluru",
    "Sri Jagadguru Chandrashekaranatha Swamiji Institute of Technology",
    "SJC Institute of Technology, Chikmagalur",
    "Malnad College of Engineering, Hassan",
    "Karnataka College of Engineering & Technology, Bangalore",
    "Global Academy of Technology, Bangalore",
    "M S Engineering College, Bangalore",
    "Rajeev Institute of Technology, Hassan",
    "Indus College of Engineering, Tumakuru",
    "Kuppam Engineering College (Karnataka affiliate)",
    "Rajalakshmi Engineering College (Karnataka campus)",
    "SDM Institute of Technology, Ujire",
    "Srinivas Institute of Technology, Mangalore",
    "BMS Institute of Technology and Management, Bangalore",
    "Sahyadri College of Engineering & Management, Mangaluru",
    "Basaveshwara College of Engineering, Bagalkot",
    "Nagarjuna College of Engineering & Technology, Bangalore",
    "Oxford College of Engineering & Technology, Bangalore",
    "Sri Sairam College of Engineering, Bangalore",
    "Rajarajeswari College of Engineering, Bangalore",
    "Shree Devi Institute of Technology, Mangalore",
    "Karnataka Institute of Technology, Dharwad",
    "Gopalan College of Engineering & Management, Bangalore",
    "Sri Ramakrishna Engineering College (Karnataka campus)",
    "Srinivas School of Engineering, Mangalore",
    "Ramanagara Engineering College, Ramanagara",
	"Dr. Ambedkar Institute of Technology, Bangalore",
	"ACS College of Engineering, Bangalore",
	"AMC Engineering College, Bangalore",
	"Atria Institute of Technology, Bangalore",
	"Bangalore Technological Institute, Bangalore",
	"Cambridge Institute of Technology, Bangalore",
	"Cambridge Institute of Technology North Campus, Bangalore",
	"Dayananda Sagar Academy of Technology and Management, Bangalore",
	"Dr. T. Thimmaiah Institute of Technology, KGF",
	"East West Institute of Technology, Bangalore",
	"GSSS Institute of Engineering and Technology for Women, Mysore",
	"Hira College of Engineering and Technology, Bangalore",
	"Impact College of Engineering and Applied Sciences, Bangalore",
	"Islamiah Institute of Technology, Bangalore",
	"JSS Science and Technology University, Mysore",
	"KLS Gogte Institute of Technology, Belagavi",
	"KS Institute of Technology, Bangalore",
	"New Horizon College of Engineering, Bangalore",
	"Presidency University School of Engineering, Bangalore",
	"Reva University School of Engineering, Bangalore",
	"Sambhram Institute of Technology, Bangalore",
	"Shree Devi Institute of Technology, Tumkur",
	"SJB Institute of Technology, Bangalore",
	"Sri Krishna Institute of Technology, Bangalore",
	"Sri Siddhartha Institute of Technology, Tumkur",
	"Sri Siddhartha Academy of Higher Education, Tumkur",
	"Sri Taralabalu Jagadguru Institute of Technology, Ranebennur",
	"St. Joseph Engineering College, Mangalore",
	"Vemana Institute of Technology, Bangalore",
	"Vidyavardhaka College of Engineering, Mysore",
	"Visvesvaraya College of Engineering and Technology, Bangalore",
	"Vivekananda College of Engineering and Technology, Puttur",
	"Yenepoya Institute of Technology, Moodbidri",
	"Rao Bahadur Y Mahabaleshwarappa Engineering College, Bellary",
	"KNS Institute of Technology, Bangalore",
	"T. John Institute of Technology, Bangalore",
	"Government Engineering College, Mandya",
	"Government Engineering College, Koppal",
	"Government Engineering College, Bidar",
	"Government Engineering College, Kalaburagi",
	"Government Engineering College, Bagalkot",
	"Government Engineering College, Davangere",
	"Government Engineering College, Tumkur",
	"Government Engineering College, Yadgir",
	"Government Engineering College, Chikkaballapur"," bmsit"
	};
		
		for(String college:colleges)
		{
			String courses[]=University.getCoursesByCollegeName(college);
			System.out.println("Courses offered in "+college+" is : ");
			if(courses!=null)
			{
				for(String course:courses)
				{
					System.out.println(course);
				}
			}
			else
			{
				System.out.println("null can't expected");
			}
		}
		
	}
}