class LegRunner
{
	public static void main(String[] val)
	{
		Leg leg=new Leg();
		Leg leg1=new Leg();
		Leg leg2=new Leg();
		Leg leg3=new Leg();
		Leg leg4=new Leg();
		Leg leg5=new Leg();
		Leg leg6=new Leg();
		Leg leg7=new Leg();
		Leg leg8=new Leg();
		Leg leg9=new Leg();
		Leg leg10=new Leg();
		Leg leg11=new Leg();
		Leg leg12=new Leg();
		Leg leg13=new Leg();
		Leg leg14=new Leg();
		Leg leg15=new Leg();
		Leg leg16=new Leg();
		Leg leg17=new Leg();
		Leg leg18=new Leg();
		Leg leg19=new Leg();
		Leg leg20=new Leg();
		Leg leg21=new Leg();
		
		
		System.out.println("default value of int size : "+leg.size);
		System.out.println("default value of int size : "+leg1.size);
		System.out.println("default value of int size : "+leg2.size);
		System.out.println("default value of int size : "+leg3.size);
		System.out.println("default value of int size : "+leg4.size);
		System.out.println("default value of int size : "+leg5.size);

		
		System.out.println("\ndefault value of float weight: "+leg.weight);
		System.out.println("default value of float weight: "+leg1.weight);
		System.out.println("default value of float weight: "+leg2.weight);
		System.out.println("default value of float weight: "+leg3.weight);
		System.out.println("default value of float weight: "+leg4.weight);
		System.out.println("default value of float weight: "+leg5.weight);
		System.out.println("-----------------------------------------------");

		leg.size=2;
		leg1.size=3;
		leg2.size=4;
		leg3.size=5;
		leg4.size=6;
		leg5.size=7;
		leg6.size=8;
		leg7.size=9;
		leg8.size=10;
		leg9.size=11;
		leg10.size=12;
		leg11.size=13;
		leg12.size=14;
		leg13.size=15;
		leg14.size=16;
		leg15.size=17;
		leg16.size=18;
		leg17.size=19;
		leg18.size=20;
		leg19.size=21;
		leg20.size=22;
		leg21.size=23;
		
		leg.weight=20.0f;
		leg1.weight=30.2f;
		leg2.weight=40.5f;
		leg3.weight=5.5f;
		leg4.weight=6.5f;
		leg5.weight=7.8f;
		leg6.weight=8.5f;
		leg7.weight=9.7f;
		leg8.weight=10.4f;
		leg9.weight=11.5f;
		leg10.weight=120.2f;
		leg11.weight=13.7f;
		leg12.weight=14.54f;
		leg13.weight=15.95f;
		leg14.weight=16.85f;
		leg15.weight=17.25f;
		leg16.weight=18.36f;
		leg17.weight=19.33f;
		leg18.weight=20.22f;
		leg19.weight=21.47f;
		leg20.weight=22.7f;
		leg21.weight=23.69f;
		
		System.out.println("\n\nupdated value of int size : "+leg.size);
		System.out.println("updated value of int size : "+leg1.size);
		System.out.println("updated value of int size : "+leg2.size);
		System.out.println("updated value of int size : "+leg3.size);
		System.out.println("updated value of int size : "+leg4.size);
		System.out.println("updated value of int size : "+leg5.size);

		
		System.out.println("\nupdated value of float weight: "+leg.weight);
		System.out.println("updated value of float weight: "+leg1.weight);
		System.out.println("updated value of float weight: "+leg2.weight);
		System.out.println("updated value of float weight: "+leg3.weight);
		System.out.println("updated value of float weight: "+leg4.weight);
		System.out.println("updated value of float weight: "+leg5.weight);
		System.out.println("-----------------------------------------------");
		
		
		Hand hand=new Hand();
		Hand hand1=new Hand();
		Hand hand2=new Hand();
		Hand hand3=new Hand();
		Hand hand4=new Hand();
		Hand hand5=new Hand();
		Hand hand6=new Hand();
		Hand hand7=new Hand();
		Hand hand8=new Hand();
		Hand hand9=new Hand();
		Hand hand10=new Hand();
		Hand hand11=new Hand();
		Hand hand12=new Hand();
		Hand hand13=new Hand();
		Hand hand14=new Hand();
		Hand hand15=new Hand();
		Hand hand16=new Hand();
		Hand hand17=new Hand();
		Hand hand18=new Hand();
		Hand hand19=new Hand();
		Hand hand20=new Hand();
		Hand hand21=new Hand();
		
		System.out.println("\ndefault value of String spell : "+hand.spell);
		System.out.println("default value of String spell : "+hand1.spell);
		System.out.println("default value of String spell : "+hand2.spell);
		System.out.println("default value of String spell : "+hand3.spell);
		System.out.println("default value of String spell : "+hand4.spell);
		System.out.println("default value of String spell : "+hand5.spell);
		
		System.out.println("\ndefault value of int length  : "+hand.length );
		System.out.println("default value of int length  : "+hand1.length );
		System.out.println("default value of int length  : "+hand2.length );
		System.out.println("default value of int length  : "+hand3.length );
		System.out.println("default value of int length  : "+hand4.length );
		System.out.println("default value of int length  : "+hand5.length );
		System.out.println("-----------------------------------------------");
		
		hand.spell="Hand";
		hand1.spell="hand";
		hand2.spell="HAnd";
		hand3.spell="HANd";
		hand4.spell="HaNd";
		hand5.spell="HaNNd";
		hand6.spell="Hannd";
		hand7.spell="Hanhd";
		hand8.spell="Handd";
		hand9.spell="Hanndd";
		hand10.spell="Hhand";
		hand11.spell="Hhhand";
		hand12.spell="Hhaand";
		hand13.spell="Hgahdnd";
		hand14.spell="Hgand";
		hand15.spell="Hfavnd";
		hand16.spell="Hvand";
		hand17.spell="Havnd";
		hand18.spell="Haend";
		hand19.spell="Hasndd";
		hand20.spell="Hnand";
		hand21.spell="Haxnd";
		
		hand.length=18;
		hand1.length=17;
		hand2.length=16;
		hand3.length=15;
		hand4.length=14;
		hand5.length=13;
		hand6.length=12;
		hand7.length=11;
		hand8.length=10;
		hand9.length=9;
		hand10.length=8;
		hand11.length=7;
		hand12.length=6;
		hand13.length=4;
		hand14.length=3;
		hand15.length=46;
		hand16.length=2;
		hand17.length=1;
		hand18.length=25;
		hand19.length=21;
		hand20.length=5;
		hand21.length=99;
		
		
		System.out.println("\nupdated value of String spell : "+hand.spell);
		System.out.println("updated value of String spell : "+hand1.spell);
		System.out.println("updated value of String spell : "+hand2.spell);
		System.out.println("updated value of String spell : "+hand3.spell);
		System.out.println("updated value of String spell : "+hand4.spell);
		System.out.println("updated value of String spell : "+hand5.spell);
		
		System.out.println("\nupdated value of int length  : "+hand.length );
		System.out.println("updated value of int length  : "+hand1.length );
		System.out.println("updated value of int length  : "+hand2.length );
		System.out.println("updated value of int length  : "+hand3.length );
		System.out.println("updated value of int length  : "+hand4.length );
		System.out.println("updated value of int length  : "+hand5.length );
		System.out.println("-----------------------------------------------");
	
	
		TShirt tshirt=new TShirt();
		TShirt tshirt1=new TShirt();
		TShirt tshirt2=new TShirt();
		TShirt tshirt3=new TShirt();
		TShirt tshirt4=new TShirt();
		TShirt tshirt5=new TShirt();
		TShirt tshirt6=new TShirt();
		TShirt tshirt7=new TShirt();
		TShirt tshirt8=new TShirt();
		TShirt tshirt9=new TShirt();
		TShirt tshirt10=new TShirt();
		TShirt tshirt11=new TShirt();
		TShirt tshirt12=new TShirt();
		TShirt tshirt13=new TShirt();
		TShirt tshirt14=new TShirt();
		TShirt tshirt15=new TShirt();
		TShirt tshirt16=new TShirt();
		TShirt tshirt17=new TShirt();
		TShirt tshirt18=new TShirt();
		TShirt tshirt19=new TShirt();
		TShirt tshirt20=new TShirt();
		TShirt tshirt21=new TShirt();

		System.out.println("\nDefault value of String brand : "+tshirt.brand);
		System.out.println("Default value of String brand : "+tshirt1.brand);
		System.out.println("Default value of String brand : "+tshirt2.brand);
		System.out.println("Default value of String brand : "+tshirt3.brand);
		System.out.println("Default value of String brand : "+tshirt4.brand);
		System.out.println("Default value of String brand : "+tshirt5.brand);

		System.out.println("\nDefault value of String size : "+tshirt.size);
		System.out.println("Default value of String size : "+tshirt1.size);
		System.out.println("Default value of String size : "+tshirt2.size);
		System.out.println("Default value of String size : "+tshirt3.size);
		System.out.println("Default value of String size : "+tshirt4.size);
		System.out.println("Default value of String size : "+tshirt5.size);
		System.out.println("-----------------------------------------------");

		tshirt.brand="Nike";
		tshirt.size="M";
		tshirt1.brand="Puma";
		tshirt1.size="L";
		tshirt2.brand="Adidas";
		tshirt2.size="S";
		tshirt3.brand="Zara";
		tshirt3.size="XL";
		tshirt4.brand="H&M";
		tshirt4.size="XXL";
		tshirt5.brand="Levis";
		tshirt5.size="M";
		tshirt6.brand="USPA";
		tshirt6.size="L";
		tshirt7.brand="Roadster";
		tshirt7.size="S";
		tshirt8.brand="AllenSolly";
		tshirt8.size="M";
		tshirt9.brand="PeterEngland";
		tshirt9.size="L";
		tshirt10.brand="Gucci";
		tshirt10.size="XL";
		tshirt11.brand="Reebok";
		tshirt11.size="M";
		tshirt12.brand="Fila";
		tshirt12.size="S";
		tshirt13.brand="Spykar";
		tshirt13.size="L";
		tshirt14.brand="Wrangler";
		tshirt14.size="XL";
		tshirt15.brand="Zudio";
		tshirt15.size="M";
		tshirt16.brand="Max";
		tshirt16.size="S";
		tshirt17.brand="RareRabbit"; 
		tshirt17.size="L";
		tshirt18.brand="CalvinKlein";
		tshirt18.size="XL";
		tshirt19.brand="Tommy";
		tshirt19.size="M";
		tshirt20.brand="HRX"; 
		tshirt20.size="S";
		tshirt21.brand="VanHeusen";
		tshirt21.size="L";
		
		System.out.println("\nUpdated value of String brand : "+tshirt.brand);
		System.out.println("Updated value of String brand : "+tshirt1.brand);
		System.out.println("Updated value of String brand : "+tshirt2.brand);
		System.out.println("Updated value of String brand : "+tshirt3.brand);
		System.out.println("Updated value of String brand : "+tshirt4.brand);
		System.out.println("Updated value of String brand : "+tshirt5.brand);

		System.out.println("\nUpdated value of String size : "+tshirt.size);
		System.out.println("Updated value of String size : "+tshirt1.size);
		System.out.println("Updated value of String size : "+tshirt2.size);
		System.out.println("Updated value of String size : "+tshirt3.size);
		System.out.println("Updated value of String size : "+tshirt4.size);
		System.out.println("Updated value of String size : "+tshirt5.size);
		System.out.println("-----------------------------------------------");


		Jeans jeans=new Jeans();
		Jeans jeans1=new Jeans();
		Jeans jeans2=new Jeans();
		Jeans jeans3=new Jeans();
		Jeans jeans4=new Jeans();
		Jeans jeans5=new Jeans();
		Jeans jeans6=new Jeans();
		Jeans jeans7=new Jeans();
		Jeans jeans8=new Jeans();
		Jeans jeans9=new Jeans();
		Jeans jeans10=new Jeans();
		Jeans jeans11=new Jeans();
		Jeans jeans12=new Jeans();
		Jeans jeans13=new Jeans();
		Jeans jeans14=new Jeans();
		Jeans jeans15=new Jeans();
		Jeans jeans16=new Jeans();
		Jeans jeans17=new Jeans();
		Jeans jeans18=new Jeans();
		Jeans jeans19=new Jeans();
		Jeans jeans20=new Jeans();
		Jeans jeans21=new Jeans();

		System.out.println("\ndefault value of String brand : "+jeans.brand);
		System.out.println("default value of String brand : "+jeans1.brand);
		System.out.println("default value of String brand : "+jeans2.brand);
		System.out.println("default value of String brand : "+jeans3.brand);
		System.out.println("default value of String brand : "+jeans4.brand);
		System.out.println("default value of String brand : "+jeans5.brand);

		System.out.println("\ndefault value of int size : "+jeans.size);
		System.out.println("default value of int size : "+jeans1.size);
		System.out.println("default value of int size : "+jeans2.size);
		System.out.println("default value of int size : "+jeans3.size);
		System.out.println("default value of int size : "+jeans4.size);
		System.out.println("default value of int size : "+jeans5.size);
		System.out.println("-----------------------------------------------");


		jeans.brand="Levis";
		jeans.size=30;
		jeans1.brand="Wrangler";
		jeans1.size=32;
		jeans2.brand="Spykar";
		jeans2.size=34;
		jeans3.brand="Pepe";
		jeans3.size=28;
		jeans4.brand="USPA";
		jeans4.size=36;
		jeans5.brand="AllenSolly";
		jeans5.size=38;
		jeans6.brand="Zara";
		jeans6.size=40;
		jeans7.brand="H&M";
		jeans7.size=42;
		jeans8.brand="Roadster";
		jeans8.size=29;
		jeans9.brand="HRX";
		jeans9.size=31;
		jeans10.brand="Puma";
		jeans10.size=33;
		jeans11.brand="Nike";
		jeans11.size=35;
		jeans12.brand="Adidas";
		jeans12.size=37;
		jeans13.brand="Max";
		jeans13.size=39;
		jeans14.brand="Gucci";
		jeans14.size=41;
		jeans15.brand="Tommy";
		jeans15.size=43;
		jeans16.brand="Zudio";
		jeans16.size=27;
		jeans17.brand="Reebok";
		jeans17.size=26;
		jeans18.brand="VanHeusen";
		jeans18.size=44;
		jeans19.brand="CalvinKlein";
		jeans19.size=45;
		jeans20.brand="PeterEngland";
		jeans20.size=46;
		jeans21.brand="RareRabbit";
		jeans21.size=47;

		System.out.println("\nupdated value of String brand : "+jeans.brand);
		System.out.println("updated value of String brand : "+jeans1.brand);
		System.out.println("updated value of String brand : "+jeans2.brand);
		System.out.println("updated value of String brand : "+jeans3.brand);
		System.out.println("updated value of String brand : "+jeans4.brand);
		System.out.println("updated value of String brand : "+jeans5.brand);

		System.out.println("\nupdated value of int size : "+jeans.size);
		System.out.println("updated value of int size : "+jeans1.size);
		System.out.println("updated value of int size : "+jeans2.size);
		System.out.println("updated value of int size : "+jeans3.size);
		System.out.println("updated value of int size : "+jeans4.size);
		System.out.println("updated value of int size : "+jeans5.size);
		System.out.println("-----------------------------------------------");

		
		Shorts shorts=new Shorts();
		Shorts shorts1=new Shorts();
		Shorts shorts2=new Shorts();
		Shorts shorts3=new Shorts();
		Shorts shorts4=new Shorts();
		Shorts shorts5=new Shorts();
		Shorts shorts6=new Shorts();
		Shorts shorts7=new Shorts();
		Shorts shorts8=new Shorts();
		Shorts shorts9=new Shorts();
		Shorts shorts10=new Shorts();
		Shorts shorts11=new Shorts();
		Shorts shorts12=new Shorts();
		Shorts shorts13=new Shorts();
		Shorts shorts14=new Shorts();
		Shorts shorts15=new Shorts();
		Shorts shorts16=new Shorts();
		Shorts shorts17=new Shorts();
		Shorts shorts18=new Shorts();
		Shorts shorts19=new Shorts();
		Shorts shorts20=new Shorts();
		Shorts shorts21=new Shorts();

		System.out.println("\ndefault value of String company : "+shorts.company);
		System.out.println("default value of String company : "+shorts1.company);
		System.out.println("default value of String company : "+shorts2.company);
		System.out.println("default value of String company : "+shorts3.company);
		System.out.println("default value of String company : "+shorts4.company);
		System.out.println("default value of String company : "+shorts5.company);

		System.out.println("\ndefault value of boolean used : "+shorts.used);
		System.out.println("default value of boolean used : "+shorts1.used);
		System.out.println("default value of boolean used : "+shorts2.used);
		System.out.println("default value of boolean used : "+shorts3.used);
		System.out.println("default value of boolean used : "+shorts4.used);
		System.out.println("default value of boolean used : "+shorts5.used);
		System.out.println("-----------------------------------------------");

		
		shorts.company="Nike";
		shorts.used=true;
		shorts1.company="Puma";
		shorts1.used=false;
		shorts2.company="Adidas";
		shorts2.used=true;
		shorts3.company="Zara";
		shorts3.used=false;
		shorts4.company="H&M";
		shorts4.used=true;
		shorts5.company="Levis";
		shorts5.used=false;
		shorts6.company="Roadster";
		shorts6.used=true;
		shorts7.company="Max";
		shorts7.used=false;
		shorts8.company="HRX";
		shorts8.used=true;
		shorts9.company="Spykar";
		shorts9.used=false;
		shorts10.company="Wrangler";
		shorts10.used=true;
		shorts11.company="Tommy";
		shorts11.used=false;
		shorts12.company="Gucci";
		shorts12.used=true;
		shorts13.company="VanHeusen";
		shorts13.used=false;
		shorts14.company="Reebok";
		shorts14.used=true;
		shorts15.company="Fila";
		shorts15.used=false;
		shorts16.company="Zudio";
		shorts16.used=true;
		shorts17.company="AllenSolly";
		shorts17.used=false;
		shorts18.company="USPA";
		shorts18.used=true;
		shorts19.company="RareRabbit";
		shorts19.used=false;
		shorts20.company="PeterEngland";
		shorts20.used=true;
		shorts21.company="CalvinKlein";
		shorts21.used=false;

		
		System.out.println("\nupdated value of String company : "+shorts.company);
		System.out.println("updated value of String company : "+shorts1.company);
		System.out.println("updated value of String company : "+shorts2.company);
		System.out.println("updated value of String company : "+shorts3.company);
		System.out.println("updated value of String company : "+shorts4.company);
		System.out.println("updated value of String company : "+shorts5.company);

		System.out.println("\nupdated value of boolean used : "+shorts.used);
		System.out.println("updated value of boolean used : "+shorts1.used);
		System.out.println("updated value of boolean used : "+shorts2.used);
		System.out.println("updated value of boolean used : "+shorts3.used);
		System.out.println("updated value of boolean used : "+shorts4.used);
		System.out.println("updated value of boolean used : "+shorts5.used);
		System.out.println("-----------------------------------------------");

	}
}